Break down individual config validation steps
Signed-off-by: Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -68,49 +68,61 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: "Report Invalid Yamlfmt Version"
+      if: inputs.yamlfmt-version == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No yamlfmt version provided" ; exit 1
+
+    - name: "Report Invalid Commit Message"
+      if: inputs.commit-message == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No commit message provided" ; exit 1
+
+    - name: "Report Invalid Commit User Name"
+      if: inputs.commit-user-name == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No commit user name provided" ; exit 1
+
+    - name: "Report Invalid Commit User Email"
+      if: inputs.commit-user-email == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No commit user email provided" ; exit 1
+
+    - name: "Report Invalid Indent Size"
+      if: inputs.indent-size == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No indent size provided" ; exit 1
+
+    - name: "Report Invalid Include Document Start Setting"
+      if: inputs.include-document-start == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No include document start setting provided" ; exit 1
+
+    - name: "Report Invalid Line Ending Type"
+      if: inputs.line-ending-type == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No line ending type provided" ; exit 1
+
+    - name: "Report Invalid Line Breaks Setting"
+      if: inputs.keep-line-breaks == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No keep line breaks setting provided" ; exit 1
+
+    - name: "Report Invalid Anchors Setting"
+      if: inputs.disallow-anchors == ''
+      shell: bash
+      run: echo "::error title=Fmtya Input Validation Error::No disallow anchors setting provided" ; exit 1
+
     - name: "Validate Configuration"
       id: config
       shell: bash
       env:
         LOG_TITLE: "Validation"
-        YAMLFMT_VERSION: ${{ inputs.yamlfmt-version }}
-        COMMIT_MESSAGE: ${{ inputs.commit-message }}
-        COMMIT_USER_NAME: ${{ inputs.commit-user-name }}
-        COMMIT_USER_EMAIL: ${{ inputs.commit-user-email }}
         SIGNOFF_ON_COMMIT: ${{ inputs.signoff-on-commit }}
         INCLUDE_FILES: ${{ inputs.include-files }}
         EXCLUDE_FILES: ${{ inputs.exclude-files }}
-        INDENT_SIZE: ${{ inputs.indent-size }}
-        INCLUDE_DOC_START: ${{ inputs.include-document-start }}
-        LINE_ENDING_TYPE: ${{ inputs.line-ending-type }}
-        KEEP_LINE_BREAKS: ${{ inputs.keep-line-breaks }}
-        DISALLOW_ANCHORS: ${{ inputs.disallow-anchors }}
       run: |
-        die() {
-          echo "::error title=${LOG_TITLE}::$@"
-          exit 1
-        }
-
-        err() {
-          echo "::warning title=${LOG_TITLE}::$@"
-        }
-
-        log() {
-          echo "::notice title=${LOG_TITLE}::$@"
-        }
-
-        [ -z "$YAMLFMT_VERSION" ] && die "No yamlfmt version provided"
-        [ -z "$COMMIT_MESSAGE" ] && die "No commit message provided"
-        [ -z "$COMMIT_USER_NAME" ] && die "No commit user name provided"
-        [ -z "$COMMIT_USER_EMAIL" ] && die "No commit user email provided"
         [ -z "$SIGNOFF_ON_COMMIT" ] &&  err "No signoff on commit provided"
-        [ -z "$INCLUDE_FILES" ] && die "No include files provided"
-        [ -z "$INDENT_SIZE" ] && die "No indent size provided"
-        [ -z "$INCLUDE_DOC_START" ] && die "No include document start setting provided"
-        [ -z "$LINE_ENDING_TYPE" ] && die "No line ending type provided"
-        [ -z "$KEEP_LINE_BREAKS" ] && die "No keep line breaks setting provided"
-        [ -z "$DISALLOW_ANCHORS" ] && die "No disallow anchors setting provided"
-
         if [ "$SIGNOFF_ON_COMMIT" = "true" ] || [ "$SIGNOFF_ON_COMMIT" = "yes" ]
         then
           echo "signoff-on-commit=true" | tee -a "$GITHUB_OUTPUT"
@@ -123,6 +135,7 @@ runs:
           echo "signoff-on-commit=false" | tee -a "$GITHUB_OUTPUT"
         fi
 
+        [ -z "$INCLUDE_FILES" ] && die "No include files provided"
         echo "include-files=$(echo "$INCLUDE_FILES" | awk 'NF>0' | jq -R | jq -R | jq -s | jq -r tostring)" | tee -a "$GITHUB_OUTPUT"
         echo "exclude-files=$(echo "$EXCLUDE_FILES" | awk 'NF>0' | jq -R | jq -R | jq -s | jq -r tostring)" | tee -a "$GITHUB_OUTPUT"
 
